import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import inviteRouter from "./invite";
import classesRouter from "./classes";
import studentsRouter from "./students";
import teachersRouter from "./teachers";
import attendanceRouter from "./attendance";
import examsRouter from "./exams";
import marksRouter from "./marks";
import noticesRouter from "./notices";
import feesRouter from "./fees";
import dashboardRouter from "./dashboard";
import parentsRouter from "./parents";
import schoolsRouter from "./schools";
import billingRouter from "./billing";
import certificatesRouter from "./certificates";
import eventsRouter from "./events";
import homeworkRouter from "./homework";
import leaveRequestsRouter from "./leave-requests";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(inviteRouter);
router.use(classesRouter);
router.use(studentsRouter);
router.use(teachersRouter);
router.use(attendanceRouter);
router.use(examsRouter);
router.use(marksRouter);
router.use(noticesRouter);
router.use(feesRouter);
router.use(dashboardRouter);
router.use(parentsRouter);
router.use(schoolsRouter);
router.use(billingRouter);
router.use(certificatesRouter);
router.use(eventsRouter);
router.use(homeworkRouter);
router.use(leaveRequestsRouter);

export default router;
